# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
#creating object - stops depreciation error from occuring
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestaddhorsemakeprediction():
  def setup_method(self, method):
   #creating object - stops depreciation error from occuring
    s=service = Service('C:/Users/oscar/Dropbox/Semester 3/Colic Web App/Version11/test/chromedriver.exe')
    self.driver = webdriver.Chrome(service=s)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testaddhorsemakeprediction(self):
    #connect to web application
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1920, 1040)

    #Sign in
    self.driver.find_element(By.CSS_SELECTOR, ".text-center").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ryangreen@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div:nth-child(1)").click()
    self.driver.find_element(By.NAME, "password").send_keys("testing123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
    self.driver.implicitly_wait(2)

    #Add horse
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.LINK_TEXT, "Add Horses").click()
    self.driver.find_element(By.NAME, "horse_name").click()
    self.driver.find_element(By.NAME, "horse_name").send_keys("test horse")
    self.driver.find_element(By.NAME, "passport_no").click()
    self.driver.find_element(By.NAME, "passport_no").send_keys("122223333444444")
    self.driver.find_element(By.NAME, "weight_kg").click()
    self.driver.find_element(By.NAME, "weight_kg").send_keys("200")
    self.driver.find_element(By.NAME, "height_cm").click()
    self.driver.find_element(By.NAME, "height_cm").send_keys("180")
    self.driver.find_element(By.NAME, "colour").click()
    self.driver.find_element(By.NAME, "colour").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(3) > .form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(3) > .form-group:nth-child(2) > .form-control").send_keys("test")
    self.driver.find_element(By.NAME, "horse_breed").click()
    self.driver.find_element(By.NAME, "horse_breed").send_keys("test")
    self.driver.find_element(By.NAME, "client_name").click()
    self.driver.find_element(By.NAME, "client_name").send_keys("test")
    self.driver.find_element(By.LINK_TEXT, "Add Horse").click()

    #make prediction
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    element = self.driver.find_element(By.LINK_TEXT, "Home")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    self.driver.find_element(By.NAME, "horse_id").click()
    dropdown = self.driver.find_element(By.NAME, "horse_id")
    dropdown.find_element(By.XPATH, "option['test horse // 122223333444444 // test']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-success")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-warning").click()

    #see individual horse prediction & download csv
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(11) > .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Download me").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-default")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()

    #see the account prediction history
    self.driver.find_element(By.LINK_TEXT, "See Prediction History").click()

    #edit horse
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(12) > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".userInfo > div").click()
    self.driver.find_element(By.NAME, "horse_name").send_keys("edit")
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(1)").click()
    self.driver.find_element(By.NAME, "passport_no").send_keys("444444444444444")
    self.driver.find_element(By.CSS_SELECTOR, ".container > div > .container").click()
    self.driver.find_element(By.NAME, "weight_kg").send_keys("300")
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(2)").click()
    self.driver.find_element(By.NAME, "height_cm").send_keys("177")
    self.driver.find_element(By.CSS_SELECTOR, ".container > div > .container").click()
    self.driver.find_element(By.NAME, "colour").send_keys("edit")
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(3) > .form-group:nth-child(2) > .form-control").send_keys("edit")
    self.driver.find_element(By.CSS_SELECTOR, ".container > div > .container").click()
    self.driver.find_element(By.NAME, "horse_breed").send_keys("edit")
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(4)").click()
    self.driver.find_element(By.NAME, "client_name").send_keys("edit")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()

    #change status of horse x3
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(14) > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(14) > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()

    #delete horse
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(14) > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(13) > .btn").click()

    #logout
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
